# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef8b1fd4335b7f23f22f2947373309b3cd08936aeede4841ca1b3854e45cc3dbf45501fb8ecddb761411c9b4c7b8a2f38f7c1d599bb9f950fc12e5c1d707b54e

test:
  secret_key_base: c7bc53fb9fce03bba43159719a68be7a0f7cefd744728e6c9ff55fd436e51b65af471f82c32c3e0abe509ac6783408cf5987955862c99e7cb0b8100aba838ba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
